const $=id=>document.getElementById(id);
const inExtension=typeof chrome!=='undefined'&&!!chrome.runtime?.id;
let token='',state=null,currentDraft=null,checkpoint=null,job=null,polling=false;
const contextDetails=document.createElement('details'),contextSummary=document.createElement('summary'),contextPreview=document.createElement('pre');
contextSummary.textContent='Review workspace metadata shared with the model';contextDetails.append(contextSummary,contextPreview);$('consent').closest('label').before(contextDetails);
function showError(e){$('error').hidden=false;$('error').textContent=e.message||String(e);}
async function api(route,body){
  if(inExtension){const r=await chrome.runtime.sendMessage({type:'BRIDGE',route,body});if(!r?.ok)throw new Error(r?.error||'Bridge unavailable');return r.data;}
  const r=await fetch(route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j;
}
function button(id,fn){$(id).onclick=async()=>{const b=$(id);b.disabled=true;$('error').hidden=true;try{await fn();}catch(e){showError(e);}finally{b.disabled=false;}};}
function text(id,value){$(id).textContent=value||'';}
function renderDraft(record){currentDraft=record;$('draft-card').hidden=false;text('component',record.draft.component==='COMPARE'?'Compare saved anchors':record.draft.component==='CLARIFY'?'Clarify your intention':'Checkpoint draft');text('interpretation',record.draft.interpretation);text('uncertainty',record.draft.uncertainty);$('next').value=record.userIntent||record.draft.nextStep;
 const nodes=[...(record.context.figma?.selection||[]),...(record.context.figma?.frames||[])];$('anchors').replaceChildren();for(const id of record.draft.anchorIds){const node=nodes.find(n=>n.id===id);if(node){const el=document.createElement('div');el.className='anchor';el.textContent=node.name;$('anchors').append(el);}}
 $('suggestions').replaceChildren();for(const value of record.draft.suggestions){const b=document.createElement('button');b.textContent=value;b.onclick=()=>{$('next').value=value;};$('suggestions').append(b);}text('trace',record.trace.map(t=>t.tool+' → '+t.status).join(' · '));
}
function renderCheckpoint(c){checkpoint=c;$('saved').hidden=false;text('saved-step',c.nextStep);if(currentDraft?.id===c.draftId){$('next').value=c.nextStep;$('draft-card').hidden=true;}}
async function refresh(){if(polling||!token)return;polling=true;try{
 state=await api('/state');text('connection',state.provider+' · '+state.model+' · '+(state.modelReady?'model configured':'model key missing')+' · local backend');
 contextPreview.textContent=JSON.stringify({...state.context,figma:state.figmaFresh?state.context.figma:null},null,2);
 const figma=state.context.figma;text('fresh',figma?(state.figmaFresh?'Figma connected':'Figma snapshot stale'):'Browser-only context');text('focus',figma?figma.fileName+' / '+figma.page.name:state.context.browser?.title||'No workspace captured');text('facts',figma?'Selected: '+(figma.selection.map(n=>n.name).join(', ')||'nothing'):'Pair the Figma adapter for real node-level context.');
 $('changes').replaceChildren();for(const change of (figma?.changes||[]).slice(-5)){const li=document.createElement('li');li.textContent=change.name+' · '+change.type.toLowerCase().replaceAll('_',' ')+' '+change.properties.join(', ');$('changes').append(li);}text('browser',state.context.browser?'Browser anchor: '+state.context.browser.title:'');
 if(!currentDraft){const latest=Object.values(state.drafts).sort((a,b)=>b.createdAt-a.createdAt)[0];if(latest&&Date.now()-latest.createdAt<600000)renderDraft(latest);}
 if(!checkpoint){const latest=Object.values(state.checkpoints).sort((a,b)=>b.savedAt-a.savedAt)[0];if(latest)renderCheckpoint(latest);}
 const latestJob=Object.values(state.jobs).filter(j=>!checkpoint||j.checkpointId===checkpoint.id).sort((a,b)=>b.createdAt-a.createdAt)[0];
 if(latestJob){job=latestJob;$('work').hidden=false;text('job-title',job.question);text('job-status',job.status+(job.error?' — '+job.error:''));$('cancel').hidden=job.status!=='running';text('result',job.result?.summary||'');text('job-trace',job.trace.map(t=>t.tool+' → '+t.status).join(' · '));$('sources').replaceChildren();for(const source of job.result?.sources||[]){const li=document.createElement('li'),a=document.createElement('a');a.textContent=source.title;a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a);$('sources').append(li);}}
 const command=Object.values(state.commands).sort((a,b)=>b.createdAt-a.createdAt)[0];if(command)text('restore-status',command.status==='pending'?(Date.now()-command.createdAt>30_000?'Restore expired. Reconnect the plugin and try again.':'Waiting for Figma to confirm navigation…'):command.status+' · '+command.message);
 }catch(e){showError(e);}finally{polling=false;}}
button('connect',async()=>{token=$('token').value.trim();if(!inExtension&&!token){const r=await fetch('/pair',{method:'POST'});token=(await r.json()).token;$('token').value=token;}if(inExtension){const r=await chrome.runtime.sendMessage({type:'SET_BRIDGE_TOKEN',token});if(!r?.ok)throw new Error(r?.error||'Pairing failed');const [tab]=await chrome.tabs.query({active:true,lastFocusedWindow:true});if(tab?.url?.startsWith('http'))await api('/browser',{title:(tab.title||'').slice(0,200),url:tab.url,tabId:tab.id});}await refresh();$('settings').open=false;});
button('reveal',async()=>{$('token').type=$('token').type==='password'?'text':'password';});
button('draft',async()=>{if(!$('consent').checked)throw new Error('Approve model sharing first.');text('agent-status','Agent is inspecting your context…');try{const r=await api('/draft',{intent:$('intent').value.trim(),consent:true});renderDraft(r);text('agent-status','Agent proposal ready. Confirm or edit your next step.');}catch(e){text('agent-status','Agent request failed. No simulated answer.');throw e;}});
button('save',async()=>{if(!currentDraft)throw new Error('Generate a draft first');const c=await api('/checkpoint',{draftId:currentDraft.id,nextStep:$('next').value});renderCheckpoint(c);text('agent-status','Checkpoint saved locally.');if(inExtension){const anchor=c.context.figma?.fileUrl?{title:c.context.figma.fileName,url:c.context.figma.fileUrl}:c.context.browser;await chrome.runtime.sendMessage({type:'USER_RESPONSE',action:'take_break',note:c.nextStep,anchor});}});
button('later',async()=>{$('draft-card').hidden=true;text('agent-status','Keep working. No task has started.');if(inExtension)await chrome.runtime.sendMessage({type:'USER_RESPONSE',action:'later'});});
button('restore',async()=>{if(!checkpoint)return;const result=await api('/restore',{checkpointId:checkpoint.id});text('restore-status',result.status==='pending'?'Waiting for Figma confirmation…':'Browser checkpoint: '+checkpoint.nextStep);if(inExtension){const r=await chrome.runtime.sendMessage({type:'RESTORE_TAB',anchor:checkpoint.context.browser,fileUrl:checkpoint.context.figma?.fileUrl});if(!r?.ok)throw new Error(r?.error||'Tab restore failed');}await refresh();});
button('research',async()=>{if(!checkpoint)throw new Error('Save your checkpoint first.');job=await api('/jobs',{checkpointId:checkpoint.id,question:$('question').value.trim(),consent:true});await refresh();});
button('cancel',async()=>{if(job)await api('/cancel',{id:job.id});await refresh();});
async function init(){if(inExtension){const stored=await chrome.storage.local.get('bridgeToken');token=stored.bridgeToken||'';$('token').value=token;const r=await chrome.runtime.sendMessage({type:'GET_STATE'});if(r?.state){text('policy',r.state.reason+' · '+Math.floor(r.state.activeSeconds/60)+' estimated active min');$('monitor').checked=r.state.enabled;$('demo').checked=r.state.demoMode;}if(token){const [tab]=await chrome.tabs.query({active:true,lastFocusedWindow:true});if(tab?.url?.startsWith('http'))await api('/browser',{title:(tab.title||'').slice(0,200),url:tab.url,tabId:tab.id});}}else{$('settings').open=true;$('monitor').disabled=true;$('demo').disabled=true;text('policy','Activity controls are available in the Chrome extension.');}if(token)await refresh();}
$('demo').onchange=async()=>{if(inExtension)await chrome.runtime.sendMessage({type:'SET_DEMO_MODE',enabled:$('demo').checked});};
$('monitor').onchange=async()=>{if(inExtension)await chrome.runtime.sendMessage({type:'SET_ENABLED',enabled:$('monitor').checked});};
init().catch(showError);setInterval(refresh,3000);
